apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - port: 80
      protocol: TCP
      targetPort: registry
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: ko://github.com/matzew/service-registry/cmd/registry
          ports:
            - containerPort: 8080
              protocol: TCP
              name: registry
